Feature/bizpack for client
mokuhara/omochi pull request #12
Opened 2021-01-17 15:38 UTC by mokuhara

不可解なエラーが出てmigrate失敗するけどとりあえずプルリク作成
```
migrate -source file://db/migrations/ -database 'mysql://root:password@tcp(127.0.0.1:3306)/omochi' up
error: Dirty database version 20210117234837. Fix and force version.
migrate -source file://db/migrations/ -database 'mysql://root:password@tcp(127.0.0.1:3306)/omochi' up force 20210117234837
error: can't read limit argument N
```

2021-01-17 15:50 UTC, inoue9951 requested changes

2021-01-17 15:50 UTC, inoue9951 commented on db/migrations/20210118003131_create_transactions.up.sql
> +CREATE TABLE IF NOT EXISTS transactions (
transactionテーブルはvideo_meeting, reviewより先に作られる必要があります(外部キーを貼るため)
golang-migrateはtimestampが若い順に実行するので、video_meeting, reviewを作成するマイグレーションファイルよりも先にtransactionsテーブルを作成するためのマイグレーションファイルを作成してください

2021-01-17 16:13 UTC, mokuhara commented on db/migrations/20210118003131_create_transactions.up.sql
> +CREATE TABLE IF NOT EXISTS transactions (
修正をコミット完了

2021-01-20 12:49 UTC, inoue9951 requested changes
外部キー設定を正しい名前でお願いします

2021-01-20 12:49 UTC, inoue9951 commented on app/models/transaction.go
> +	ClientUserID int64 `json:"clientUserId"`
client_id, specialist_idに変更して外部キーを設定してください
マイグレートファイルも合わせて修正してください
bond側でも修正がある場合はそちらもお願いします

2021-01-21 05:29 UTC, merged