Feature/create transaction
mokuhara/omochi pull request #3
Opened 2020-12-22 13:38 UTC by mokuhara

transaction作成

2020-12-28 08:43 UTC, inoue9951 requested changes
コントローラが巨大すぎるので、リソース別にファイル分けてあげた方が良いと思います

2020-12-28 08:43 UTC, inoue9951 commented on app/controller/mypage/transaction.go
> +func CreatePayment(c *gin.Context){
transaction以外のエンドポイントをtransactionコントローラに持たせるのはちょっと詰め込みすぎかと思います
この場合は`controller/mypage/transactions/payment.go`みたいな感じでファイル分けてあげるのが良いと思います

2020-12-28 08:43 UTC, inoue9951 commented on app/repository/payment.go
> +	db := DBCon()
dbはmodel共通で定義してあげても良いかもしれないですね

2020-12-30 01:33 UTC, mokuhara commented on app/controller/mypage/transaction.go
> +func CreatePayment(c *gin.Context){
分割しておく

2020-12-30 01:34 UTC, mokuhara commented on app/repository/payment.go
> +	db := DBCon()
たしかになー、のちにリファクタするか

2020-12-30 10:17 UTC, merged